#!/bin/csh -f
#

if ( !(-e wfsStart) )then
   ln -s ./bin/solaris/wfsStart .
endif

if ( !(-e wfsStart2) )then
   ln -s ./bin/solaris/wfsStart2 .
endif

applSetup -T mv167 -s Makefile.subdirs -I docs -I dspsrc -I par -X sys -X ar \
          -depends /gemini/astlib -depends /gemini/slalib -depends /gemini/timelib \
          -depends /gemini/cfitsio -depends /gemini/dhs

# Because of the "-I's" in the above line...

applSetup
