# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions

include Target.include
include .applTop/config/CONFIG

# Insert this alternative compiler to use purify, otherwise comment out.
#CC = purify gcc -B$(VX_GNU_LIB)/gcc-lib/ -nostdinc
#LD = -o

# External libraries on which this directory is dependent.
# DEPLIBS      =

# User compiler and loader flags (NO_EPICS flag is needed for all processors except zero)
# SNC_FLAGS    =
# USR_CFLAGS   = -DNO_EPICS
# USR_CFLAGS = -DDEBUG -g
# USR_CFLAGS = -g
# (sysextLib and mpPipeDrv are not compatible with present hardware).
USR_CFLAGS = -DNO_SYSEXTLIB -DNO_MPPIPEDRV -O2
# USR_INCLUDES =
# USR_LDFLAGS  =
# USR_LDLIBS   =

# Add the source code files to this variable. The default has all .c files.
# The AGWPS source files are divided into library and application, with the
# library modules being combined into one downloadable object file.
# Combining the libraries reduces the overall loading time.
#SRCS.c	= $(wildcard ../*.c)
LIBSRCS.c	= \
	../cicsCarHealth.c \
	../cicsLib.c \
	../epToVxLibHrwfs.c \
	../errorLib.c \
	../ospInvertFuncs.c \
	../ospLib.c \
	../sdsuLib.c \
	../timeoutLib.c \
	../wfsLib.c \
	../wfsWcs.c \
	../writeZernikes.c

APPLSRCS.c	= \
	../detControl.c \
	../simpleLogHrwfs.c \
	../wfsControl.c \
	../wfsHrwfsDb.c \
	../wfsResourceMonitor.c \
	../wfsSite.c \
	../testHarness.c \
	../testKit.c \
	../sdsuRead.c \
	../strcasecmp.c \
	../fpscr.c \
	../dhstests.c

SRCS.c	= $(LIBSRCS.c) $(APPLSRCS.c)


# Add the object files in one of these two variables. 
# LIBOBJS += test.o
LIBOBJS	=  $(strip $(patsubst ../%.c,    %.o, $(LIBSRCS.c)))
OBJS	=  $(strip $(patsubst ../%.c,    %.o, $(APPLSRCS.c))             \
		   $(patsubst ../%.st,   %.o, $(wildcard ../*.st  )) \
		   $(patsubst ../%.stpp, %.o, $(wildcard ../*.stpp)))

# Standard macros for files which are to be built and installed.
# PROD (products) and SCRIPTS are installed in INSTALL_BIN
PROD	= $(strip $(patsubst %.o, %, $(OBJS))                        \
		  $(patsubst ../%.vws, %, $(wildcard ../*.vws)))
SCRIPTS	=

# LIBNAME is installed in INSTALL_LIB
LIBNAME	= wfsLibrariesHrwfs

# INC is installed in INSTALL_INCLUDE
# Add the public header files to this variable. The default has all .h files.
#INC	= $(wildcard ../*.h)
INC	= \
	../wfsHrwfsDb.h

# MAN1 is installed in INSTALL_MAN/man1
MAN1	=

# DOCS are installed in INSTALL_DOC
DOCS	=

# DATA are installed in INSTALL_DATA
DATA	=

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)
TARGETS	=

# Rules for building targets
include .applTop/config/RULES.Build

# There is no product rule, but one can be added and edited.
#$(PROD): $(OBJS)
#	$(RM) $@
#	$(LINK.c) $@ $(OBJS)
#

# I attempted to build statTbl with the following additions, but it didn't work.
#statTbl: ../statTbl.c
#	$(GCC_EXEC_PREFIX) $(ARCH_DEP_CFLAGS) ../statTbl.c
#
#statTbl.c: $(INC)
#	$(VX_DIR)/bin/solaris/makeStatTbl ..
