#!/bin/csh -f
ln -s ../../src/cicsCarHealth.c .
ln -s ../../src/cicsLib.c .
ln -s ../../src/epToVxLib.c .
ln -s ../../src/errorLib.c .
ln -s ../../src/ospInvertFuncs.c .
ln -s ../../src/ospLib.c .
ln -s ../../src/sdsuLib.c .
ln -s ../../src/timeoutLib.c .
ln -s ../../src/wfsLib.c .
ln -s ../../src/wfsWcs.c .
ln -s ../../src/writeZernikes.c .
